### ISSUE TITLE
how to convert to pgm

### ISSUE THREAD

**Issue by Heiseyoumoo** [RavuAlHemio/PbmNet#1]
How to use this to convert jpg, png, bmp to pgm ,Thx .

**Comment by RavuAlHemio** [comment]
Hi!

PbmNet only concerns itself with loading and writing Netpbm files; loading/writing other formats or doing anything with the loaded pixels is outside of its purview. To load a JPEG, PNG or BMP file, you will have to use a different library; here is some sample code using System.Drawing:

```c#
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using RavuAlHemio.PbmNet;

namespace ScaleImage
{
    class Program
    {
        static IEnumerable<List<byte>> MakeRowsFrom(Bitmap bmp)
        {
            for (int row = 0; row < bmp.Height; ++row)
            {
                var rowList = new List<byte>(4 * bmp.Width);
                for (int col = 0; col < bmp.Width; ++col)
                {
                    Color pixel = bmp.GetPixel(col, row);
                    rowList.Add(pixel.R);
                    rowList.Add(pixel.G);
                    rowList.Add(pixel.B);
                    rowList.Add(pixel.A);
                }
                yield return rowList;
            }
        }

        static void Main(string[] args)
        {
            var inputImage = (Bitmap)Image.FromFile(@"C:\Windows\ImmersiveControlPanel\images\phone.png");

            var outputHeader = new NetpbmHeader<byte>(
                imageType: ImageType.PAM,
                width: inputImage.Width, height: inputImage.Height,
                bytesPerPixelComponent: 1,
                components: new[] {Component.Red, Component.Green, Component.Blue, Component.Alpha},
                highestComponentValue: 255
            );
            var outputImage = new NetpbmImage8(
                outputHeader,
                MakeRowsFrom(inputImage)
            );
            var outputWriter = new NetpbmWriter();
            using (var outputStream = new FileStream("phone.pam", FileMode.Create))
            {
                outputWriter.WriteImage(outputImage, outputStream, outputImage.Header.ImageType);
            }
        }
    }
}
```

You could optimize this further by using `System.Drawing.Bitmap.LockBits()` and `System.Drawing.Imaging.BitmapData`, but that makes the code quite harder to understand at a quick glance.

**Comment by Heiseyoumoo** [comment]
Thank you very much for your reply, I tried your code, can turn into pam, but turn pgm wrong.

My goal is bitmap conversion vector graphics, previously thought to be jpg png bmp-> pgm-> svg.
Now I find someone on github that can be implemented http: /potrace.sourceforge.net/.

Rasterbater 1.0 can be implemented but it doesn't work very well. I continue to study potrace.
Thank you very much again for your reply.

**Comment by RavuAlHemio** [comment]
PGM, the "portable graymap", only allows for grayscale images -- you would have to somehow convert from the JPEG/PNG/BMP containing RGB or RGBA data to an image containing only grayscale ("lightness") data, and that's a task for an image processing library.

potrace has modes that allow tracing color images as well, so you'll probably have more luck using it instead of the intermediate PGM step.

I'll close this issue; feel free to reopen it if your question hasn't been answered.
